import Footer from "@/components/Footer";
import Header from "@/components/Header";
import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "./globals.css";

const inter = Inter({
	variable: "--font-inter",
	subsets: ["latin"],
});

const roboto = Roboto({
	variable: "--font-roboto",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="fr" className="h-full">
			<body
				className={`${inter.variable} ${roboto.variable} antialiased h-full flex flex-col min-h-screen`}
			>
				<Header />
				<div className="flex-1">{children}</div>
				{/* <Footer /> */}
			</body>
		</html>
	);
}

